In [25]:
import numpy as np
import time

In [9]:
# vectors 
a = np.array([1,1,1,1,1,1])
b = np.array([2,2,2,2,2,2])
X = np.array([[3,3,3,3,3,3],
              [3,3,3,3,3,3],
              [3,3,3,3,3,3],
              [3,3,3,3,3,3]])
Z = np.array([[4,4,4,4,4,4],
             [4,4,4,4,4,4],
             [4,4,4,4,4,4]])

In [10]:
#1b and 1c
y = a@b
print(y)

12


In [11]:
#1d 

y = a@X.T
print(y)

[18 18 18 18]


In [12]:
#1e 

a_tmp = np.tile(a, (4,1))
y = np.sum(a_tmp * X, axis=1)
print(np.sum(y))

72


In [13]:
#1f 

y = Z@X.T
print(y)

[[72 72 72 72]
 [72 72 72 72]
 [72 72 72 72]]


In [18]:
#1g

# sample matrices
x = np.array([
    [0.85010961, 0.196843  , 0.62482917],
    [0.43200093, 0.84558781, 0.15000539],
    [0.52065869, 0.52032799, 0.06452433],
    [0.31393462, 0.49788737, 0.39832731],
    [0.742627  , 0.6549765 , 0.02164187]
])

w = np.array([
    [0.87635738, 0.43876443, 0.6723783 ],
    [0.83112752, 0.7563367 , 0.70536239],
    [0.58914038, 0.70466684, 0.46502848],
    [0.32523603, 0.18626796, 0.88806008]
])

a = np.array([0.71051815, 0.080134  , 0.51579408, 0.50644482])

v = x@w.T
v.shape

y = v@a
y


array([1.91242856, 1.38575315, 1.11377203, 1.26431798, 1.43007651])

In [24]:
#1h 
def matrix_mul(x, w):
    if x.shape[1] != w.shape[0]:
        raise ValueError("Matrix dimensions do not match")
    result = np.zeros((x.shape[0], w.shape[1]))
    for indexr, row in enumerate(result):
        for indexc, col in enumerate(row):
            result[indexr][indexc] = np.dot(x[indexr], w[:,indexc])
    return result


print(matrix_mul(x, w.T))
print(x@w.T)

[[1.25148911 1.29616007 0.93010599 0.86803766]
 [0.85046143 1.10440512 0.92012366 0.43122198]
 [0.72796926 0.87178996 0.70340459 0.32355888]
 [0.76140083 0.9184553  0.72102982 0.5485819 ]
 [0.95273857 1.12786586 0.90911586 0.38274947]]
[[1.25148911 1.29616007 0.93010599 0.86803766]
 [0.85046143 1.10440512 0.92012366 0.43122198]
 [0.72796926 0.87178996 0.70340459 0.32355888]
 [0.76140083 0.9184553  0.72102982 0.5485819 ]
 [0.95273857 1.12786586 0.90911586 0.38274947]]


In [32]:
#1i

def matrix_mul_symmetric(A):
    N = A.shape[1]
    result = np.zeros((N, N))
    for i in range(N):
        for j in range(i, N):
            result[i, j] = np.dot(A[:, i], A[:, j])
            if i != j:
                result[j, i] = result[i, j]
    return result

A = np.random.randint(low=0, high=10, size=(1000,100))


start_time = time.time()
ATA_self = matrix_mul(A,A.T)
custom_time = time.time() - start_time


start_time = time.time()
ATA_custom = matrix_mul_symmetric(A)
builtin_time = time.time() - start_time

custom_time, builtin_time

(2.598328113555908, 0.03175830841064453)